[tool.poetry]
name = "skypro-shop"
version = "0.1.0"
description = ""
authors = ["Chernokozov Yuriy <Chernokozovyu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^6.0"
pillow = "^12.0.0"
psycopg2-binary = "^2.9.11"
python-dotenv = "^1.2.1"
ipython = "^9.8.0"


[tool.poetry.group.lint.dependencies]
black = "^25.11.0"
flake8 = "^7.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
